from __future__ import annotations

import re
from dataclasses import dataclass
from html import unescape
from typing import Protocol
from urllib.parse import urljoin, urlparse
from xml.etree import ElementTree

from software_multiagent.software_memory.acquisition.models import DocumentationSource, SourceDocument


class DiscoveryTransport(Protocol):
    def fetch(self, url: str, *, timeout: float, max_bytes: int): ...  # type: ignore[no-untyped-def]


class DiscoveryUrlPolicy(Protocol):
    def validate(self, url: str, source: DocumentationSource) -> str: ...
    def is_crawl_candidate(self, url: str, source: DocumentationSource) -> bool: ...


@dataclass(frozen=True)
class DiscoveryResult:
    platform: str
    strategies: tuple[str, ...]
    urls: tuple[str, ...]


def _decode(content: bytes, content_type: str = "") -> str:
    match = re.search(r"charset=([\w-]+)", content_type, re.I)
    return content.decode(match.group(1) if match else "utf-8", errors="replace")


class AutoCorpusDiscovery:
    """Platform-aware route discovery with generic, reusable strategies."""

    def __init__(self, transport: DiscoveryTransport, policy: DiscoveryUrlPolicy) -> None:
        self.transport = transport
        self.policy = policy

    def discover(
        self,
        source: DocumentationSource,
        initial_response,
        initial_document: SourceDocument,
    ) -> DiscoveryResult:
        urls: dict[str, set[str]] = {}
        strategies: list[str] = []

        def add(values, strategy: str) -> None:  # type: ignore[no-untyped-def]
            added = False
            for value in values:
                try:
                    clean = self.policy.validate(value, source)
                except (OSError, ValueError):
                    continue
                if self.policy.is_crawl_candidate(clean, source):
                    urls.setdefault(clean, set()).add(strategy)
                    added = True
            if added and strategy not in strategies:
                strategies.append(strategy)

        add((initial_document.canonical_url, *initial_document.links), "html_links")

        html = _decode(initial_response.content, initial_response.headers.get("content-type", ""))
        platform = self._detect_platform(html)
        sitemap_urls = self._discover_sitemaps(source)
        add(sitemap_urls, "sitemap")
        if platform == "docusaurus":
            add(self._discover_docusaurus_routes(source, initial_document.canonical_url, html), "docusaurus_routes")

        return DiscoveryResult(
            platform=platform,
            strategies=tuple(strategies),
            urls=tuple(sorted(urls)),
        )

    @staticmethod
    def _detect_platform(html: str) -> str:
        lowered = html.lower()
        if "__docusaurus" in lowered or "docusaurus" in lowered:
            return "docusaurus"
        if "generated by doxygen" in lowered:
            return "doxygen"
        if "swagger-ui" in lowered or "redoc" in lowered:
            return "openapi-ui"
        if "sphinx" in lowered:
            return "sphinx"
        if "mkdocs" in lowered:
            return "mkdocs"
        return "generic"

    def _discover_sitemaps(self, source: DocumentationSource) -> tuple[str, ...]:
        parsed = urlparse(source.url)
        origin = f"{parsed.scheme}://{parsed.netloc}"
        version_root = parsed.path.rstrip("/")
        candidates = [f"{origin}/sitemap.xml"]
        if version_root:
            candidates.append(f"{origin}{version_root}/sitemap.xml")
        discovered: list[str] = []
        visited: set[str] = set()
        queue = candidates[:]
        while queue and len(visited) < 10:
            sitemap = queue.pop(0)
            if sitemap in visited:
                continue
            visited.add(sitemap)
            try:
                self.policy.validate(sitemap, source)
                response = self.transport.fetch(
                    sitemap,
                    timeout=source.timeout_seconds,
                    max_bytes=min(source.max_response_bytes, 5_000_000),
                )
                if not 200 <= response.status < 300:
                    continue
                root = ElementTree.fromstring(response.content)
            except (ElementTree.ParseError, OSError, ValueError):
                continue
            locations = [
                (node.text or "").strip()
                for node in root.iter()
                if node.tag.rsplit("}", 1)[-1] == "loc" and node.text
            ]
            if root.tag.rsplit("}", 1)[-1] == "sitemapindex":
                queue.extend(locations)
            else:
                discovered.extend(locations)
        return tuple(discovered)

    def _discover_docusaurus_routes(
        self, source: DocumentationSource, page_url: str, html: str
    ) -> tuple[str, ...]:
        script_sources = re.findall(
            r"<script\b[^>]*\bsrc=[\"']([^\"']+)[\"']", html, flags=re.I
        )
        candidates = [
            urljoin(page_url, unescape(value))
            for value in script_sources
            if re.search(r"(?:^|/)main(?:\.[a-z0-9_-]+)?\.js(?:\?|$)", value, re.I)
        ]
        routes: set[str] = set()
        for script_url in candidates[:5]:
            try:
                self.policy.validate(script_url, source)
                response = self.transport.fetch(
                    script_url,
                    timeout=source.timeout_seconds,
                    max_bytes=min(max(source.max_response_bytes, 2_000_000), 10_000_000),
                )
                if not 200 <= response.status < 300:
                    continue
            except (OSError, ValueError):
                continue
            javascript = _decode(response.content, response.headers.get("content-type", ""))
            for route in re.findall(
                r"(?:[\"']?path[\"']?|[\"']?permalink[\"']?)\s*:\s*[\"'](/[^\"']*)[\"']",
                javascript,
            ):
                if any(marker in route for marker in ("*", ":", "\\")):
                    continue
                routes.add(urljoin(page_url, route))
        return tuple(sorted(routes))
